approve_by_comment: true
approve_regex: '^(Approved|:\+1:)'
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - aaronjudd
  - jshimko
  - mikemurray
  - zenweasel
  - kieckhafer
  - Capt-Slow
  - rymorgan
  name: pullapprove
  required: 2
